[build]
publish = "site"
command = """
restore_home_cache ".cache" "pip cache" &&
restore_cwd_cache '.venv' 'python virtualenv' &&
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
mkdocs build -d site
"""
# [build]
# publish = "site"
# command = "pip install -e . && gomplate -d adopters=./data/adopters.yaml -f templates/adopters.md -o docs/project/adopters.md && mkdocs build"

[build.environment]
PYTHON_VERSION = "3.11"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

# [context.production]
# command = "pip install -e . && mkdocs build"
#
# [context.deploy-preview]
# command = "pip install -e . && mkdocs build"
